const FAILED = 'FAILED';
const ERROR = 'ERROR';
const MY_CUSTOM_EXCEPTION = 'MY_CUSTOM_EXCEPTION';

const USER_NOT_EXIST = 'USER_NOT_EXIST';
const THIS_USERNAME_OR_PASSWORD_IS_INCORRECT =
	'THIS_USERNAME_OR_PASSWORD_IS_INCORRECT';
const SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG';

const PASSWORD_MUST_BE_8_120_CHARACTERS_LONG =
	'PASSWORD_MUST_BE_{8-120}_CHARACTERS_LONG';

const PASSWORD_MUST_NOT_CONTAIN_WHITE_SPACES =
	'PASSWORD_MUST_NOT_CONTAIN_WHITE_SPACES';

const PASSWORD_MUST_HAVE_AT_LEAST_ONE_LOWERCASE_CHARACTER =
	'PASSWORD_MUST_HAVE_AT_LEAST_ONE_LOWERCASE_CHARACTER';

const PASSWORD_MUST_HAVE_AT_LEAST_ONE_UPPERCASE_CHARACTER =
	'PASSWORD_MUST_HAVE_AT_LEAST_ONE_UPPERCASE_CHARACTER';

const PASSWORD_MUST_CONTAIN_AT_LEAST_ONE_DIGIT =
	'PASSWORD_MUST_CONTAIN_AT_LEAST_ONE_DIGIT';

const PASSWORD_MUST_CONTAIN_AT_LEAST_ONE_SPECIAL_SYMBOL =
	'PASSWORD_MUST_CONTAIN_AT_LEAST_ONE_SPECIAL_SYMBOL';

const NOT_PROVIDE_BEARER_TOKEN = 'NOT_PROVIDE_BEARER_TOKEN';
const NOT_LOGGED_IN = 'NOT_LOGGED_IN';

module.exports = {
	FAILED,
	ERROR,
	MY_CUSTOM_EXCEPTION,
	USER_NOT_EXIST,
	THIS_USERNAME_OR_PASSWORD_IS_INCORRECT,
	SOMETHING_WENT_WRONG,
	PASSWORD_MUST_BE_8_120_CHARACTERS_LONG,
	PASSWORD_MUST_NOT_CONTAIN_WHITE_SPACES,
	PASSWORD_MUST_HAVE_AT_LEAST_ONE_LOWERCASE_CHARACTER,
	PASSWORD_MUST_HAVE_AT_LEAST_ONE_UPPERCASE_CHARACTER,
	PASSWORD_MUST_CONTAIN_AT_LEAST_ONE_DIGIT,
	PASSWORD_MUST_CONTAIN_AT_LEAST_ONE_SPECIAL_SYMBOL,
	NOT_PROVIDE_BEARER_TOKEN,
	NOT_LOGGED_IN,
};
